version: '3.1'

services:
  finder-mongodb:
    image: mongo:${MONGODB_VERSION}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PWD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - mongo-finder-volume:/data/db
    hostname: finder-mongodb

  finder-mongoadmin:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=finder-mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PWD}
    ports:
      - '8082:8081'
    restart: unless-stopped

  finder-redis:
    image: redis:${REDIS_VERSION}
    restart: always
    hostname: ${REDIS_HOST}
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis-finder-volume:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '8081:8081'

volumes:
  mongo-finder-volume:
    external: true
  redis-finder-volume:
